apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cmawebservice }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.cmawebapplicationName }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP


